spring:
  application:
    name: discovery-server
  config:
    activate:
      on-profile: prod
  cloud:
    config:
      server:
        git:
          uri:
          default-label: prod
          search-paths: prod
eureka:
  server:
    peer-node-read-timeout-ms: 2000
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: ${EUREKA_INSTANCE_HOST:localhost}
server:
  port: ${EUREKA_PORT:8761}
management:
  endpoints:
    web:
      exposure:
        include: health