spring:
  application:
    name: discovery-server
  config:
    activate:
      on-profile: dev
  cloud:
    config:
      server:
        git:
          uri:
          default-label: dev
          search-paths: dev
eureka:
  server:
    peer-node-read-timeout-ms: 2000
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: localhost
server:
  port: 8761
management:
  endpoints:
    web:
      exposure:
        include: health